# Generated by Django 3.2.4 on 2023-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
