# Generated by Django 3.2.4 on 2023-01-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_document_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='body',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='sections',
            name='text_file',
            field=models.FileField(max_length=254, upload_to='pdfs/'),
        ),
    ]
