# Generated by Django 3.2.4 on 2023-01-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20230125_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc',
            new_name='pdf',
        ),
    ]
