# Generated by Django 3.2.4 on 2023-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_rename_doc_document_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='key',
        ),
        migrations.AlterField(
            model_name='sections',
            name='text_file',
            field=models.FileField(upload_to=None),
        ),
    ]
