# Generated by Django 3.2.4 on 2023-02-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20230126_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.document'),
        ),
    ]
