# Generated by Django 3.2.4 on 2023-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_sections_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='text_file',
            field=models.FileField(upload_to=''),
        ),
    ]
