# Generated by Django 3.2.4 on 2023-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_alter_document_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='sections',
            name='text_file',
            field=models.FileField(upload_to=None),
        ),
    ]
